In [1]:
pip install chefboost

Defaulting to user installation because normal site-packages is not writeable
Collecting chefboost
  Downloading chefboost-0.0.17-py3-none-any.whl (26 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\programdata\anaconda3\lib\site-packages (from chefboost) (1.21.5)
Requirement already satisfied: pandas>=0.22.0 in c:\programdata\anaconda3\lib\site-packages (from chefboost) (1.4.4)
Requirement already satisfied: psutil>=5.4.3 in c:\programdata\anaconda3\lib\site-packages (from chefboost) (5.9.0)
Requirement already satisfied: tqdm>=4.30.0 in c:\programdata\anaconda3\lib\site-packages (from chefboost) (4.64.1)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->chefboost) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->chefboost) (2.8.2)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.30.0->chefboost) (0.4.5)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=0.22.0->chefboost) (1.16.0)
Installing collected packages: chefboost
Successfully installed chefboost-0.0.17
Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/chefboost/

In [2]:
from chefboost import Chefboost as chef
import pandas as pd

In [4]:
df = pd.read_csv("C:\\Users\\Abarna V\\Desktop\\End semester AML Laboratory (Dataset)\\ID3\\balloondataset.csv")
df

     Color   Size      Act    Age Inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  CHILD        T
2   YELLOW  SMALL      DIP  ADULT        T
3   YELLOW  SMALL      DIP  CHILD        T
4   YELLOW  LARGE  STRETCH  ADULT        T
5   YELLOW  LARGE  STRETCH  CHILD        F
6   YELLOW  LARGE      DIP  ADULT        F
7   YELLOW  LARGE      DIP  CHILD        F
8   PURPLE  SMALL  STRETCH  ADULT        T
9   PURPLE  SMALL  STRETCH  CHILD        F
10  PURPLE  SMALL      DIP  ADULT        F
11  PURPLE  SMALL      DIP  CHILD        F
12  PURPLE  LARGE  STRETCH  ADULT        T
13  PURPLE  LARGE  STRETCH  CHILD        F
14  PURPLE  LARGE      DIP  ADULT        F
15  PURPLE  LARGE      DIP  CHILD        F

In [5]:
config = {'algorithm': 'ID3'}
model = chef.fit(df, config = config, target_label = 'Inflated')
df

[INFO]:  4 CPU cores will be allocated in parallel running
ID3  tree is going to be built...
-------------------------
finished in  1.9062137603759766  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  100.0 % on  16  instances
Labels:  ['T' 'F']
Confusion matrix:  [[7, 0], [0, 9]]
Precision:  100.0 %, Recall:  100.0 %, F1:  100.0 %

     Color   Size      Act    Age Inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  CHILD        T
2   YELLOW  SMALL      DIP  ADULT        T
3   YELLOW  SMALL      DIP  CHILD        T
4   YELLOW  LARGE  STRETCH  ADULT        T
5   YELLOW  LARGE  STRETCH  CHILD        F
6   YELLOW  LARGE      DIP  ADULT        F
7   YELLOW  LARGE      DIP  CHILD        F
8   PURPLE  SMALL  STRETCH  ADULT        T
9   PURPLE  SMALL  STRETCH  CHILD        F
10  PURPLE  SMALL      DIP  ADULT        F
11  PURPLE  SMALL      DIP  CHILD        F
12  PURPLE  LARGE  STRETCH  ADULT        T
13  PURPLE  LARGE  STRETCH  CHILD        F
14  PURPLE  LARGE      DIP  ADULT        F
15  PURPLE  LARGE      DIP  CHILD        F

In [6]:
prediction = chef.predict(model, param = ['PURPLE', 'SMALL', 'STRETCH', 'ADULT'])
prediction

'T'

In [7]:
prediction = chef.predict(model, param = ['PURPLE', 'SMALL', 'STRETCH', 'CHILD'])
prediction

'F'